---
version: '3.8'

services:
  docusaurus:
    container_name: docusaurus
    image: docusaurus
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - .:/home/app
